// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxBRKu5j2gAbuDpj-RppQBIr2SNE7SWec',
    appId: '1:916586785452:web:6e100e70f6b7d87df0cd09',
    messagingSenderId: '916586785452',
    projectId: 'medisimbio-patient',
    authDomain: 'medisimbio-patient.firebaseapp.com',
    storageBucket: 'medisimbio-patient.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwXXPlVpG643_2opiY7bpyO4WAaRFjjZI',
    appId: '1:916586785452:android:32ab479489d4cf4ff0cd09',
    messagingSenderId: '916586785452',
    projectId: 'medisimbio-patient',
    storageBucket: 'medisimbio-patient.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJE7vzGj-LJkUhpGpeaY-iGK7SfHpDUk',
    appId: '1:916586785452:ios:fa4ab4bc21d59784f0cd09',
    messagingSenderId: '916586785452',
    projectId: 'medisimbio-patient',
    storageBucket: 'medisimbio-patient.firebasestorage.app',
    iosBundleId: 'com.example.medisimbio',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJE7vzGj-LJkUhpGpeaY-iGK7SfHpDUk',
    appId: '1:916586785452:ios:fa4ab4bc21d59784f0cd09',
    messagingSenderId: '916586785452',
    projectId: 'medisimbio-patient',
    storageBucket: 'medisimbio-patient.firebasestorage.app',
    iosBundleId: 'com.example.medisimbio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxBRKu5j2gAbuDpj-RppQBIr2SNE7SWec',
    appId: '1:916586785452:web:5c50571d374dcd63f0cd09',
    messagingSenderId: '916586785452',
    projectId: 'medisimbio-patient',
    authDomain: 'medisimbio-patient.firebaseapp.com',
    storageBucket: 'medisimbio-patient.firebasestorage.app',
  );
}
